app:
  title: GitOps Management Portal
  baseUrl: http://localhost:3000

organization:
  name: RadiantLogic

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: localhost
      port: 5432
      user: backstage
      password: backstage
      database: backstage

auth:
  environment: development
  # Session secret for signing cookies (generate with: openssl rand -base64 32)
  session:
    secret: ${AUTH_SESSION_SECRET}
  # Guest authentication for development (no OAuth required)
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
    # GitHub OAuth
    github:
      development:
        clientId: ${GITHUB_OAUTH_CLIENT_ID}
        clientSecret: ${GITHUB_OAUTH_CLIENT_SECRET}
        ## uncomment if using GitHub Enterprise
        # enterpriseInstanceUrl: ${GITHUB_ENTERPRISE_URL}
    # Google OAuth
    google:
      development:
        clientId: ${GOOGLE_OAUTH_CLIENT_ID}
        clientSecret: ${GOOGLE_OAUTH_CLIENT_SECRET}
    # Microsoft OAuth (Azure AD) via oauth2 provider
    oauth2:
      development:
        clientId: ${MICROSOFT_OAUTH_CLIENT_ID}
        clientSecret: ${MICROSOFT_OAUTH_CLIENT_SECRET}
        authorizationUrl: https://login.microsoftonline.com/${MICROSOFT_TENANT_ID}/oauth2/v2.0/authorize
        tokenUrl: https://login.microsoftonline.com/${MICROSOFT_TENANT_ID}/oauth2/v2.0/token
        scope: openid email profile

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

# GitOps Plugin Configuration
gitops:
  github:
    organization: radiantlogic-saas
    token: ${GITHUB_TOKEN}
  argocd:
    enabled: true
    url: ${ARGOCD_URL}
    token: ${ARGOCD_TOKEN}
  grafana:
    enabled: true
    url: ${GRAFANA_URL}
    token: ${GRAFANA_TOKEN}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Group, User]
  locations:
    - type: file
      target: ./catalog-entities.yaml

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'
