apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "backstage-gitops.labels" . | nindent 4 }}
type: Opaque
stringData:
  # These values should be provided during installation
  # Either via --set or a separate values file
  # Example:
  #   helm install backstage-gitops ./helm \
  #     --set secrets.githubToken="your-token" \
  #     --set secrets.postgresPassword="your-password" \
  #     --set secrets.argoCdToken="your-argocd-token"

  # Or create the secret manually before installing the chart:
  #   kubectl create secret generic backstage-secrets \
  #     --from-literal=GITHUB_TOKEN='your-token' \
  #     --from-literal=POSTGRES_PASSWORD='your-password' \
  #     --from-literal=ARGOCD_TOKEN='your-argocd-token'

  # Placeholder values - MUST be overridden
  {{ .Values.secrets.githubToken.key }}: ""
  {{ .Values.secrets.postgresPassword.key }}: ""
  {{- if .Values.argocd.enabled }}
  {{ .Values.secrets.argoCdToken.key }}: ""
  {{- end }}
