{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage-gitops.postgres.fullname" . }}
  labels:
    {{- include "backstage-gitops.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "backstage-gitops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
