'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useOrganizationStore } from '@/store/organization-store';
import { OrgBanner } from '@/components/dashboard/org-banner';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from '@/components/ui/table';
import { RefreshCw, ExternalLink, AlertCircle, Layers } from 'lucide-react';
import { toast } from 'sonner';

interface ApplicationSetItem {
  name: string;
  namespace: string;
  generators: string[];
  templateProject?: string;
  templateRepoURL?: string;
  appCount: number;
  resourceVersion?: string;
  externalUrl: string;
}

export default function ApplicationSetsPage() {
  const orgId = useOrganizationStore((s) => s.currentOrganization?.id);
  const [items, setItems] = useState<ApplicationSetItem[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState('');
  const [syncingName, setSyncingName] = useState<string | null>(null);

  const load = useCallback(async () => {
    if (!orgId) {
      setItems([]);
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/argocd/applicationsets', {
        headers: { 'x-organization-id': orgId },
      });
      const body = await res.json();
      if (!res.ok) {
        setError(body?.error?.message || `HTTP ${res.status}`);
        setItems(null);
        return;
      }
      setItems(body.data ?? []);
    } catch (e) {
      setError((e as Error).message);
      setItems(null);
    } finally {
      setLoading(false);
    }
  }, [orgId]);

  useEffect(() => {
    void load();
  }, [load]);

  const filtered = useMemo(() => {
    if (!items) return [];
    const q = filter.trim().toLowerCase();
    if (!q) return items;
    return items.filter(
      (s) =>
        s.name.toLowerCase().includes(q) ||
        s.generators.some((g) => g.toLowerCase().includes(q)),
    );
  }, [items, filter]);

  async function handleSync(name: string) {
    if (!orgId) return;
    if (!window.confirm(`Sync all applications generated by "${name}"? This can affect production.`)) {
      return;
    }
    setSyncingName(name);
    try {
      const res = await fetch(`/api/argocd/applicationsets/${encodeURIComponent(name)}/sync`, {
        method: 'POST',
        headers: { 'x-organization-id': orgId },
      });
      const body = await res.json();
      if (!res.ok) {
        toast.error(body?.error?.message || `Sync failed (HTTP ${res.status})`);
        return;
      }
      const { targeted, succeeded, failed } = body.data || {};
      toast.success(`${succeeded}/${targeted} synced (${failed} failed)`);
      await load();
    } catch (e) {
      toast.error((e as Error).message);
    } finally {
      setSyncingName(null);
    }
  }

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col gap-2">
        <OrgBanner />
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">ApplicationSets</h1>
            <p className="text-sm text-muted-foreground mt-1">
              Browse ArgoCD ApplicationSets and trigger fan-out sync of their generated applications.
            </p>
          </div>
          <Button onClick={() => void load()} disabled={loading || !orgId} size="sm" variant="outline">
            <RefreshCw className={`h-4 w-4 mr-2 ${loading ? 'animate-spin' : ''}`} />
            Refresh
          </Button>
        </div>
      </div>

      <Input
        placeholder="Filter by name or generator…"
        value={filter}
        onChange={(e) => setFilter(e.target.value)}
        className="max-w-md"
      />

      {error && (
        <Card className="border-destructive bg-destructive/5">
          <CardContent className="pt-6 flex items-start gap-2">
            <AlertCircle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />
            <div>
              <p className="font-medium text-destructive">Failed to load ApplicationSets</p>
              <p className="text-sm text-muted-foreground mt-1">{error}</p>
              <Button variant="outline" size="sm" className="mt-2" onClick={() => void load()}>Retry</Button>
            </div>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle className="text-sm font-medium">
            {items === null ? '—' : items.length} ApplicationSets
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <div className="overflow-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Name</TableHead>
                  <TableHead>Namespace</TableHead>
                  <TableHead>Generators</TableHead>
                  <TableHead>Template Project</TableHead>
                  <TableHead>Apps</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {loading && items === null ? (
                  Array.from({ length: 3 }).map((_, i) => (
                    <TableRow key={i}>
                      <TableCell colSpan={6}>
                        <Skeleton className="h-5 w-full" />
                      </TableCell>
                    </TableRow>
                  ))
                ) : filtered.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={6} className="text-center py-12 text-muted-foreground">
                      <Layers className="h-10 w-10 mx-auto mb-3 opacity-30" />
                      {!orgId
                        ? 'Select an organization to load ApplicationSets'
                        : items && items.length === 0
                          ? 'No ApplicationSets defined'
                          : 'No matches'}
                    </TableCell>
                  </TableRow>
                ) : (
                  filtered.map((s) => (
                    <TableRow key={`${s.namespace}/${s.name}`}>
                      <TableCell className="font-medium">
                        <a
                          href={s.externalUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="hover:underline inline-flex items-center gap-1"
                        >
                          {s.name}
                          <ExternalLink className="h-3 w-3 opacity-60" />
                        </a>
                      </TableCell>
                      <TableCell>
                        <Badge variant="secondary">{s.namespace}</Badge>
                      </TableCell>
                      <TableCell>
                        <div className="flex flex-wrap gap-1">
                          {s.generators.length === 0 ? (
                            <span className="text-xs text-muted-foreground">—</span>
                          ) : (
                            s.generators.map((g) => (
                              <Badge key={g} variant="outline" className="text-[10px]">{g}</Badge>
                            ))
                          )}
                        </div>
                      </TableCell>
                      <TableCell className="text-muted-foreground">{s.templateProject || '—'}</TableCell>
                      <TableCell>{s.appCount}</TableCell>
                      <TableCell className="text-right">
                        <Button
                          variant="outline"
                          size="sm"
                          disabled={syncingName === s.name}
                          onClick={() => void handleSync(s.name)}
                        >
                          {syncingName === s.name ? (
                            <RefreshCw className="h-3.5 w-3.5 animate-spin" />
                          ) : (
                            'Sync all'
                          )}
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
