{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "devops-portal.fullname" . }}-externalsecret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devops-portal.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ required "externalSecrets.storeRef.name is required when externalSecrets.enabled=true" .Values.externalSecrets.storeRef.name | quote }}
    kind: {{ .Values.externalSecrets.storeRef.kind | default "ClusterSecretStore" | quote }}
  target:
    name: {{ .Values.externalSecrets.targetSecretName | default "devops-portal-secrets" | quote }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.data | nindent 4 }}
{{- end }}

