// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: devops_portal/agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Agent_AgentMetadata_FullMethodName           = "/devops_portal.agent.v1.Agent/AgentMetadata"
	Agent_Heartbeat_FullMethodName               = "/devops_portal.agent.v1.Agent/Heartbeat"
	Agent_RenewCert_FullMethodName               = "/devops_portal.agent.v1.Agent/RenewCert"
	Agent_ListNodes_FullMethodName               = "/devops_portal.agent.v1.Agent/ListNodes"
	Agent_ListNamespaces_FullMethodName          = "/devops_portal.agent.v1.Agent/ListNamespaces"
	Agent_ListPods_FullMethodName                = "/devops_portal.agent.v1.Agent/ListPods"
	Agent_GetPod_FullMethodName                  = "/devops_portal.agent.v1.Agent/GetPod"
	Agent_ListWorkloads_FullMethodName           = "/devops_portal.agent.v1.Agent/ListWorkloads"
	Agent_ListServices_FullMethodName            = "/devops_portal.agent.v1.Agent/ListServices"
	Agent_ListIngresses_FullMethodName           = "/devops_portal.agent.v1.Agent/ListIngresses"
	Agent_ListEvents_FullMethodName              = "/devops_portal.agent.v1.Agent/ListEvents"
	Agent_ListCRDs_FullMethodName                = "/devops_portal.agent.v1.Agent/ListCRDs"
	Agent_GetYaml_FullMethodName                 = "/devops_portal.agent.v1.Agent/GetYaml"
	Agent_StreamPodLogs_FullMethodName           = "/devops_portal.agent.v1.Agent/StreamPodLogs"
	Agent_WatchEvents_FullMethodName             = "/devops_portal.agent.v1.Agent/WatchEvents"
	Agent_ArgoListApplications_FullMethodName    = "/devops_portal.agent.v1.Agent/ArgoListApplications"
	Agent_ArgoGetApplication_FullMethodName      = "/devops_portal.agent.v1.Agent/ArgoGetApplication"
	Agent_ArgoListAppProjects_FullMethodName     = "/devops_portal.agent.v1.Agent/ArgoListAppProjects"
	Agent_ArgoListApplicationSets_FullMethodName = "/devops_portal.agent.v1.Agent/ArgoListApplicationSets"
	Agent_PromQuery_FullMethodName               = "/devops_portal.agent.v1.Agent/PromQuery"
	Agent_PromQueryRange_FullMethodName          = "/devops_portal.agent.v1.Agent/PromQueryRange"
	Agent_PromListAlerts_FullMethodName          = "/devops_portal.agent.v1.Agent/PromListAlerts"
	Agent_PromListTargets_FullMethodName         = "/devops_portal.agent.v1.Agent/PromListTargets"
	Agent_GrafanaListDashboards_FullMethodName   = "/devops_portal.agent.v1.Agent/GrafanaListDashboards"
	Agent_GrafanaGetDashboard_FullMethodName     = "/devops_portal.agent.v1.Agent/GrafanaGetDashboard"
	Agent_GrafanaListDataSources_FullMethodName  = "/devops_portal.agent.v1.Agent/GrafanaListDataSources"
	Agent_LokiQuery_FullMethodName               = "/devops_portal.agent.v1.Agent/LokiQuery"
	Agent_LokiQueryRange_FullMethodName          = "/devops_portal.agent.v1.Agent/LokiQueryRange"
	Agent_ESListIndices_FullMethodName           = "/devops_portal.agent.v1.Agent/ESListIndices"
	Agent_ESSearch_FullMethodName                = "/devops_portal.agent.v1.Agent/ESSearch"
	Agent_ESHealth_FullMethodName                = "/devops_portal.agent.v1.Agent/ESHealth"
	Agent_OSListIndices_FullMethodName           = "/devops_portal.agent.v1.Agent/OSListIndices"
	Agent_OSSearch_FullMethodName                = "/devops_portal.agent.v1.Agent/OSSearch"
	Agent_OSHealth_FullMethodName                = "/devops_portal.agent.v1.Agent/OSHealth"
	Agent_KibanaListSavedObjects_FullMethodName  = "/devops_portal.agent.v1.Agent/KibanaListSavedObjects"
	Agent_KibanaListDashboards_FullMethodName    = "/devops_portal.agent.v1.Agent/KibanaListDashboards"
	Agent_FluentdGetMetrics_FullMethodName       = "/devops_portal.agent.v1.Agent/FluentdGetMetrics"
	Agent_FluentdGetPlugins_FullMethodName       = "/devops_portal.agent.v1.Agent/FluentdGetPlugins"
	Agent_ReportAuditCounts_FullMethodName       = "/devops_portal.agent.v1.Agent/ReportAuditCounts"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	// Lifecycle
	AgentMetadata(ctx context.Context, in *AgentMetadataRequest, opts ...grpc.CallOption) (*AgentMetadataResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	RenewCert(ctx context.Context, in *RenewCertRequest, opts ...grpc.CallOption) (*RenewCertResponse, error)
	// K8s read RPCs
	ListNodes(ctx context.Context, in *K8SListRequest, opts ...grpc.CallOption) (*NodesResponse, error)
	ListNamespaces(ctx context.Context, in *K8SListRequest, opts ...grpc.CallOption) (*NamespacesResponse, error)
	ListPods(ctx context.Context, in *K8SListPodsRequest, opts ...grpc.CallOption) (*PodsResponse, error)
	GetPod(ctx context.Context, in *K8SGetPodRequest, opts ...grpc.CallOption) (*Pod, error)
	ListWorkloads(ctx context.Context, in *K8SListRequest, opts ...grpc.CallOption) (*WorkloadsResponse, error)
	ListServices(ctx context.Context, in *K8SListRequest, opts ...grpc.CallOption) (*ServicesResponse, error)
	ListIngresses(ctx context.Context, in *K8SListRequest, opts ...grpc.CallOption) (*IngressesResponse, error)
	ListEvents(ctx context.Context, in *K8SListRequest, opts ...grpc.CallOption) (*EventsResponse, error)
	ListCRDs(ctx context.Context, in *K8SListRequest, opts ...grpc.CallOption) (*CRDsResponse, error)
	GetYaml(ctx context.Context, in *K8SGetYamlRequest, opts ...grpc.CallOption) (*YamlResponse, error)
	// Streaming
	StreamPodLogs(ctx context.Context, in *StreamPodLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
	WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Service adapters (read-only Phase 1)
	ArgoListApplications(ctx context.Context, in *ArgoListAppsRequest, opts ...grpc.CallOption) (*ArgoApplicationsResponse, error)
	ArgoGetApplication(ctx context.Context, in *ArgoGetAppRequest, opts ...grpc.CallOption) (*ArgoApplication, error)
	ArgoListAppProjects(ctx context.Context, in *ArgoListProjectsRequest, opts ...grpc.CallOption) (*ArgoAppProjectsResponse, error)
	ArgoListApplicationSets(ctx context.Context, in *ArgoListAppSetsRequest, opts ...grpc.CallOption) (*ArgoApplicationSetsResponse, error)
	PromQuery(ctx context.Context, in *PromQueryRequest, opts ...grpc.CallOption) (*PromQueryResponse, error)
	PromQueryRange(ctx context.Context, in *PromQueryRangeRequest, opts ...grpc.CallOption) (*PromQueryResponse, error)
	PromListAlerts(ctx context.Context, in *PromListAlertsRequest, opts ...grpc.CallOption) (*PromAlertsResponse, error)
	PromListTargets(ctx context.Context, in *PromListTargetsRequest, opts ...grpc.CallOption) (*PromTargetsResponse, error)
	GrafanaListDashboards(ctx context.Context, in *GrafanaListDashboardsRequest, opts ...grpc.CallOption) (*GrafanaDashboardsResponse, error)
	GrafanaGetDashboard(ctx context.Context, in *GrafanaGetDashboardRequest, opts ...grpc.CallOption) (*GrafanaDashboard, error)
	GrafanaListDataSources(ctx context.Context, in *GrafanaListDataSourcesRequest, opts ...grpc.CallOption) (*GrafanaDataSourcesResponse, error)
	LokiQuery(ctx context.Context, in *LokiQueryRequest, opts ...grpc.CallOption) (*LokiQueryResponse, error)
	LokiQueryRange(ctx context.Context, in *LokiQueryRangeRequest, opts ...grpc.CallOption) (*LokiQueryResponse, error)
	ESListIndices(ctx context.Context, in *ESListIndicesRequest, opts ...grpc.CallOption) (*ESIndicesResponse, error)
	ESSearch(ctx context.Context, in *ESSearchRequest, opts ...grpc.CallOption) (*ESSearchResponse, error)
	ESHealth(ctx context.Context, in *ESHealthRequest, opts ...grpc.CallOption) (*ESHealthResponse, error)
	OSListIndices(ctx context.Context, in *ESListIndicesRequest, opts ...grpc.CallOption) (*ESIndicesResponse, error)
	OSSearch(ctx context.Context, in *ESSearchRequest, opts ...grpc.CallOption) (*ESSearchResponse, error)
	OSHealth(ctx context.Context, in *ESHealthRequest, opts ...grpc.CallOption) (*ESHealthResponse, error)
	KibanaListSavedObjects(ctx context.Context, in *KibanaListSavedObjectsRequest, opts ...grpc.CallOption) (*KibanaSavedObjectsResponse, error)
	KibanaListDashboards(ctx context.Context, in *KibanaListDashboardsRequest, opts ...grpc.CallOption) (*KibanaDashboardsResponse, error)
	FluentdGetMetrics(ctx context.Context, in *FluentdMetricsRequest, opts ...grpc.CallOption) (*FluentdMetricsResponse, error)
	FluentdGetPlugins(ctx context.Context, in *FluentdPluginsRequest, opts ...grpc.CallOption) (*FluentdPluginsResponse, error)
	// Audit reconciliation
	ReportAuditCounts(ctx context.Context, in *ReportAuditCountsRequest, opts ...grpc.CallOption) (*ReportAuditCountsResponse, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) AgentMetadata(ctx context.Context, in *AgentMetadataRequest, opts ...grpc.CallOption) (*AgentMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentMetadataResponse)
	err := c.cc.Invoke(ctx, Agent_AgentMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Agent_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) RenewCert(ctx context.Context, in *RenewCertRequest, opts ...grpc.CallOption) (*RenewCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewCertResponse)
	err := c.cc.Invoke(ctx, Agent_RenewCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListNodes(ctx context.Context, in *K8SListRequest, opts ...grpc.CallOption) (*NodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodesResponse)
	err := c.cc.Invoke(ctx, Agent_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListNamespaces(ctx context.Context, in *K8SListRequest, opts ...grpc.CallOption) (*NamespacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespacesResponse)
	err := c.cc.Invoke(ctx, Agent_ListNamespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListPods(ctx context.Context, in *K8SListPodsRequest, opts ...grpc.CallOption) (*PodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PodsResponse)
	err := c.cc.Invoke(ctx, Agent_ListPods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetPod(ctx context.Context, in *K8SGetPodRequest, opts ...grpc.CallOption) (*Pod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pod)
	err := c.cc.Invoke(ctx, Agent_GetPod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListWorkloads(ctx context.Context, in *K8SListRequest, opts ...grpc.CallOption) (*WorkloadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadsResponse)
	err := c.cc.Invoke(ctx, Agent_ListWorkloads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListServices(ctx context.Context, in *K8SListRequest, opts ...grpc.CallOption) (*ServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServicesResponse)
	err := c.cc.Invoke(ctx, Agent_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListIngresses(ctx context.Context, in *K8SListRequest, opts ...grpc.CallOption) (*IngressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngressesResponse)
	err := c.cc.Invoke(ctx, Agent_ListIngresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListEvents(ctx context.Context, in *K8SListRequest, opts ...grpc.CallOption) (*EventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventsResponse)
	err := c.cc.Invoke(ctx, Agent_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListCRDs(ctx context.Context, in *K8SListRequest, opts ...grpc.CallOption) (*CRDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CRDsResponse)
	err := c.cc.Invoke(ctx, Agent_ListCRDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetYaml(ctx context.Context, in *K8SGetYamlRequest, opts ...grpc.CallOption) (*YamlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YamlResponse)
	err := c.cc.Invoke(ctx, Agent_GetYaml_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StreamPodLogs(ctx context.Context, in *StreamPodLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[0], Agent_StreamPodLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPodLogsRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_StreamPodLogsClient = grpc.ServerStreamingClient[LogChunk]

func (c *agentClient) WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[1], Agent_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_WatchEventsClient = grpc.ServerStreamingClient[Event]

func (c *agentClient) ArgoListApplications(ctx context.Context, in *ArgoListAppsRequest, opts ...grpc.CallOption) (*ArgoApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArgoApplicationsResponse)
	err := c.cc.Invoke(ctx, Agent_ArgoListApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ArgoGetApplication(ctx context.Context, in *ArgoGetAppRequest, opts ...grpc.CallOption) (*ArgoApplication, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArgoApplication)
	err := c.cc.Invoke(ctx, Agent_ArgoGetApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ArgoListAppProjects(ctx context.Context, in *ArgoListProjectsRequest, opts ...grpc.CallOption) (*ArgoAppProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArgoAppProjectsResponse)
	err := c.cc.Invoke(ctx, Agent_ArgoListAppProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ArgoListApplicationSets(ctx context.Context, in *ArgoListAppSetsRequest, opts ...grpc.CallOption) (*ArgoApplicationSetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArgoApplicationSetsResponse)
	err := c.cc.Invoke(ctx, Agent_ArgoListApplicationSets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) PromQuery(ctx context.Context, in *PromQueryRequest, opts ...grpc.CallOption) (*PromQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromQueryResponse)
	err := c.cc.Invoke(ctx, Agent_PromQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) PromQueryRange(ctx context.Context, in *PromQueryRangeRequest, opts ...grpc.CallOption) (*PromQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromQueryResponse)
	err := c.cc.Invoke(ctx, Agent_PromQueryRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) PromListAlerts(ctx context.Context, in *PromListAlertsRequest, opts ...grpc.CallOption) (*PromAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromAlertsResponse)
	err := c.cc.Invoke(ctx, Agent_PromListAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) PromListTargets(ctx context.Context, in *PromListTargetsRequest, opts ...grpc.CallOption) (*PromTargetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromTargetsResponse)
	err := c.cc.Invoke(ctx, Agent_PromListTargets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GrafanaListDashboards(ctx context.Context, in *GrafanaListDashboardsRequest, opts ...grpc.CallOption) (*GrafanaDashboardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrafanaDashboardsResponse)
	err := c.cc.Invoke(ctx, Agent_GrafanaListDashboards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GrafanaGetDashboard(ctx context.Context, in *GrafanaGetDashboardRequest, opts ...grpc.CallOption) (*GrafanaDashboard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrafanaDashboard)
	err := c.cc.Invoke(ctx, Agent_GrafanaGetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GrafanaListDataSources(ctx context.Context, in *GrafanaListDataSourcesRequest, opts ...grpc.CallOption) (*GrafanaDataSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrafanaDataSourcesResponse)
	err := c.cc.Invoke(ctx, Agent_GrafanaListDataSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) LokiQuery(ctx context.Context, in *LokiQueryRequest, opts ...grpc.CallOption) (*LokiQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LokiQueryResponse)
	err := c.cc.Invoke(ctx, Agent_LokiQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) LokiQueryRange(ctx context.Context, in *LokiQueryRangeRequest, opts ...grpc.CallOption) (*LokiQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LokiQueryResponse)
	err := c.cc.Invoke(ctx, Agent_LokiQueryRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ESListIndices(ctx context.Context, in *ESListIndicesRequest, opts ...grpc.CallOption) (*ESIndicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ESIndicesResponse)
	err := c.cc.Invoke(ctx, Agent_ESListIndices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ESSearch(ctx context.Context, in *ESSearchRequest, opts ...grpc.CallOption) (*ESSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ESSearchResponse)
	err := c.cc.Invoke(ctx, Agent_ESSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ESHealth(ctx context.Context, in *ESHealthRequest, opts ...grpc.CallOption) (*ESHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ESHealthResponse)
	err := c.cc.Invoke(ctx, Agent_ESHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) OSListIndices(ctx context.Context, in *ESListIndicesRequest, opts ...grpc.CallOption) (*ESIndicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ESIndicesResponse)
	err := c.cc.Invoke(ctx, Agent_OSListIndices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) OSSearch(ctx context.Context, in *ESSearchRequest, opts ...grpc.CallOption) (*ESSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ESSearchResponse)
	err := c.cc.Invoke(ctx, Agent_OSSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) OSHealth(ctx context.Context, in *ESHealthRequest, opts ...grpc.CallOption) (*ESHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ESHealthResponse)
	err := c.cc.Invoke(ctx, Agent_OSHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) KibanaListSavedObjects(ctx context.Context, in *KibanaListSavedObjectsRequest, opts ...grpc.CallOption) (*KibanaSavedObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KibanaSavedObjectsResponse)
	err := c.cc.Invoke(ctx, Agent_KibanaListSavedObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) KibanaListDashboards(ctx context.Context, in *KibanaListDashboardsRequest, opts ...grpc.CallOption) (*KibanaDashboardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KibanaDashboardsResponse)
	err := c.cc.Invoke(ctx, Agent_KibanaListDashboards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) FluentdGetMetrics(ctx context.Context, in *FluentdMetricsRequest, opts ...grpc.CallOption) (*FluentdMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FluentdMetricsResponse)
	err := c.cc.Invoke(ctx, Agent_FluentdGetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) FluentdGetPlugins(ctx context.Context, in *FluentdPluginsRequest, opts ...grpc.CallOption) (*FluentdPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FluentdPluginsResponse)
	err := c.cc.Invoke(ctx, Agent_FluentdGetPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ReportAuditCounts(ctx context.Context, in *ReportAuditCountsRequest, opts ...grpc.CallOption) (*ReportAuditCountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportAuditCountsResponse)
	err := c.cc.Invoke(ctx, Agent_ReportAuditCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
type AgentServer interface {
	// Lifecycle
	AgentMetadata(context.Context, *AgentMetadataRequest) (*AgentMetadataResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	RenewCert(context.Context, *RenewCertRequest) (*RenewCertResponse, error)
	// K8s read RPCs
	ListNodes(context.Context, *K8SListRequest) (*NodesResponse, error)
	ListNamespaces(context.Context, *K8SListRequest) (*NamespacesResponse, error)
	ListPods(context.Context, *K8SListPodsRequest) (*PodsResponse, error)
	GetPod(context.Context, *K8SGetPodRequest) (*Pod, error)
	ListWorkloads(context.Context, *K8SListRequest) (*WorkloadsResponse, error)
	ListServices(context.Context, *K8SListRequest) (*ServicesResponse, error)
	ListIngresses(context.Context, *K8SListRequest) (*IngressesResponse, error)
	ListEvents(context.Context, *K8SListRequest) (*EventsResponse, error)
	ListCRDs(context.Context, *K8SListRequest) (*CRDsResponse, error)
	GetYaml(context.Context, *K8SGetYamlRequest) (*YamlResponse, error)
	// Streaming
	StreamPodLogs(*StreamPodLogsRequest, grpc.ServerStreamingServer[LogChunk]) error
	WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[Event]) error
	// Service adapters (read-only Phase 1)
	ArgoListApplications(context.Context, *ArgoListAppsRequest) (*ArgoApplicationsResponse, error)
	ArgoGetApplication(context.Context, *ArgoGetAppRequest) (*ArgoApplication, error)
	ArgoListAppProjects(context.Context, *ArgoListProjectsRequest) (*ArgoAppProjectsResponse, error)
	ArgoListApplicationSets(context.Context, *ArgoListAppSetsRequest) (*ArgoApplicationSetsResponse, error)
	PromQuery(context.Context, *PromQueryRequest) (*PromQueryResponse, error)
	PromQueryRange(context.Context, *PromQueryRangeRequest) (*PromQueryResponse, error)
	PromListAlerts(context.Context, *PromListAlertsRequest) (*PromAlertsResponse, error)
	PromListTargets(context.Context, *PromListTargetsRequest) (*PromTargetsResponse, error)
	GrafanaListDashboards(context.Context, *GrafanaListDashboardsRequest) (*GrafanaDashboardsResponse, error)
	GrafanaGetDashboard(context.Context, *GrafanaGetDashboardRequest) (*GrafanaDashboard, error)
	GrafanaListDataSources(context.Context, *GrafanaListDataSourcesRequest) (*GrafanaDataSourcesResponse, error)
	LokiQuery(context.Context, *LokiQueryRequest) (*LokiQueryResponse, error)
	LokiQueryRange(context.Context, *LokiQueryRangeRequest) (*LokiQueryResponse, error)
	ESListIndices(context.Context, *ESListIndicesRequest) (*ESIndicesResponse, error)
	ESSearch(context.Context, *ESSearchRequest) (*ESSearchResponse, error)
	ESHealth(context.Context, *ESHealthRequest) (*ESHealthResponse, error)
	OSListIndices(context.Context, *ESListIndicesRequest) (*ESIndicesResponse, error)
	OSSearch(context.Context, *ESSearchRequest) (*ESSearchResponse, error)
	OSHealth(context.Context, *ESHealthRequest) (*ESHealthResponse, error)
	KibanaListSavedObjects(context.Context, *KibanaListSavedObjectsRequest) (*KibanaSavedObjectsResponse, error)
	KibanaListDashboards(context.Context, *KibanaListDashboardsRequest) (*KibanaDashboardsResponse, error)
	FluentdGetMetrics(context.Context, *FluentdMetricsRequest) (*FluentdMetricsResponse, error)
	FluentdGetPlugins(context.Context, *FluentdPluginsRequest) (*FluentdPluginsResponse, error)
	// Audit reconciliation
	ReportAuditCounts(context.Context, *ReportAuditCountsRequest) (*ReportAuditCountsResponse, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) AgentMetadata(context.Context, *AgentMetadataRequest) (*AgentMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AgentMetadata not implemented")
}
func (UnimplementedAgentServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentServer) RenewCert(context.Context, *RenewCertRequest) (*RenewCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewCert not implemented")
}
func (UnimplementedAgentServer) ListNodes(context.Context, *K8SListRequest) (*NodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedAgentServer) ListNamespaces(context.Context, *K8SListRequest) (*NamespacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNamespaces not implemented")
}
func (UnimplementedAgentServer) ListPods(context.Context, *K8SListPodsRequest) (*PodsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPods not implemented")
}
func (UnimplementedAgentServer) GetPod(context.Context, *K8SGetPodRequest) (*Pod, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPod not implemented")
}
func (UnimplementedAgentServer) ListWorkloads(context.Context, *K8SListRequest) (*WorkloadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkloads not implemented")
}
func (UnimplementedAgentServer) ListServices(context.Context, *K8SListRequest) (*ServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedAgentServer) ListIngresses(context.Context, *K8SListRequest) (*IngressesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIngresses not implemented")
}
func (UnimplementedAgentServer) ListEvents(context.Context, *K8SListRequest) (*EventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedAgentServer) ListCRDs(context.Context, *K8SListRequest) (*CRDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCRDs not implemented")
}
func (UnimplementedAgentServer) GetYaml(context.Context, *K8SGetYamlRequest) (*YamlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetYaml not implemented")
}
func (UnimplementedAgentServer) StreamPodLogs(*StreamPodLogsRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamPodLogs not implemented")
}
func (UnimplementedAgentServer) WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedAgentServer) ArgoListApplications(context.Context, *ArgoListAppsRequest) (*ArgoApplicationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArgoListApplications not implemented")
}
func (UnimplementedAgentServer) ArgoGetApplication(context.Context, *ArgoGetAppRequest) (*ArgoApplication, error) {
	return nil, status.Error(codes.Unimplemented, "method ArgoGetApplication not implemented")
}
func (UnimplementedAgentServer) ArgoListAppProjects(context.Context, *ArgoListProjectsRequest) (*ArgoAppProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArgoListAppProjects not implemented")
}
func (UnimplementedAgentServer) ArgoListApplicationSets(context.Context, *ArgoListAppSetsRequest) (*ArgoApplicationSetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArgoListApplicationSets not implemented")
}
func (UnimplementedAgentServer) PromQuery(context.Context, *PromQueryRequest) (*PromQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PromQuery not implemented")
}
func (UnimplementedAgentServer) PromQueryRange(context.Context, *PromQueryRangeRequest) (*PromQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PromQueryRange not implemented")
}
func (UnimplementedAgentServer) PromListAlerts(context.Context, *PromListAlertsRequest) (*PromAlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PromListAlerts not implemented")
}
func (UnimplementedAgentServer) PromListTargets(context.Context, *PromListTargetsRequest) (*PromTargetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PromListTargets not implemented")
}
func (UnimplementedAgentServer) GrafanaListDashboards(context.Context, *GrafanaListDashboardsRequest) (*GrafanaDashboardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrafanaListDashboards not implemented")
}
func (UnimplementedAgentServer) GrafanaGetDashboard(context.Context, *GrafanaGetDashboardRequest) (*GrafanaDashboard, error) {
	return nil, status.Error(codes.Unimplemented, "method GrafanaGetDashboard not implemented")
}
func (UnimplementedAgentServer) GrafanaListDataSources(context.Context, *GrafanaListDataSourcesRequest) (*GrafanaDataSourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrafanaListDataSources not implemented")
}
func (UnimplementedAgentServer) LokiQuery(context.Context, *LokiQueryRequest) (*LokiQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LokiQuery not implemented")
}
func (UnimplementedAgentServer) LokiQueryRange(context.Context, *LokiQueryRangeRequest) (*LokiQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LokiQueryRange not implemented")
}
func (UnimplementedAgentServer) ESListIndices(context.Context, *ESListIndicesRequest) (*ESIndicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ESListIndices not implemented")
}
func (UnimplementedAgentServer) ESSearch(context.Context, *ESSearchRequest) (*ESSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ESSearch not implemented")
}
func (UnimplementedAgentServer) ESHealth(context.Context, *ESHealthRequest) (*ESHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ESHealth not implemented")
}
func (UnimplementedAgentServer) OSListIndices(context.Context, *ESListIndicesRequest) (*ESIndicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OSListIndices not implemented")
}
func (UnimplementedAgentServer) OSSearch(context.Context, *ESSearchRequest) (*ESSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OSSearch not implemented")
}
func (UnimplementedAgentServer) OSHealth(context.Context, *ESHealthRequest) (*ESHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OSHealth not implemented")
}
func (UnimplementedAgentServer) KibanaListSavedObjects(context.Context, *KibanaListSavedObjectsRequest) (*KibanaSavedObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KibanaListSavedObjects not implemented")
}
func (UnimplementedAgentServer) KibanaListDashboards(context.Context, *KibanaListDashboardsRequest) (*KibanaDashboardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KibanaListDashboards not implemented")
}
func (UnimplementedAgentServer) FluentdGetMetrics(context.Context, *FluentdMetricsRequest) (*FluentdMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FluentdGetMetrics not implemented")
}
func (UnimplementedAgentServer) FluentdGetPlugins(context.Context, *FluentdPluginsRequest) (*FluentdPluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FluentdGetPlugins not implemented")
}
func (UnimplementedAgentServer) ReportAuditCounts(context.Context, *ReportAuditCountsRequest) (*ReportAuditCountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAuditCounts not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call panics, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_AgentMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AgentMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_AgentMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AgentMetadata(ctx, req.(*AgentMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_RenewCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).RenewCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_RenewCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).RenewCert(ctx, req.(*RenewCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListNodes(ctx, req.(*K8SListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListNamespaces(ctx, req.(*K8SListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListPods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SListPodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListPods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListPods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListPods(ctx, req.(*K8SListPodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetPod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SGetPodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetPod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetPod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetPod(ctx, req.(*K8SGetPodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListWorkloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListWorkloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListWorkloads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListWorkloads(ctx, req.(*K8SListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListServices(ctx, req.(*K8SListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListIngresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListIngresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListIngresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListIngresses(ctx, req.(*K8SListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListEvents(ctx, req.(*K8SListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListCRDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListCRDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListCRDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListCRDs(ctx, req.(*K8SListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetYaml_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SGetYamlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetYaml(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetYaml_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetYaml(ctx, req.(*K8SGetYamlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StreamPodLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPodLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).StreamPodLogs(m, &grpc.GenericServerStream[StreamPodLogsRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_StreamPodLogsServer = grpc.ServerStreamingServer[LogChunk]

func _Agent_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).WatchEvents(m, &grpc.GenericServerStream[WatchEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_WatchEventsServer = grpc.ServerStreamingServer[Event]

func _Agent_ArgoListApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArgoListAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ArgoListApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ArgoListApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ArgoListApplications(ctx, req.(*ArgoListAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ArgoGetApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArgoGetAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ArgoGetApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ArgoGetApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ArgoGetApplication(ctx, req.(*ArgoGetAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ArgoListAppProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArgoListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ArgoListAppProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ArgoListAppProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ArgoListAppProjects(ctx, req.(*ArgoListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ArgoListApplicationSets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArgoListAppSetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ArgoListApplicationSets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ArgoListApplicationSets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ArgoListApplicationSets(ctx, req.(*ArgoListAppSetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_PromQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PromQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_PromQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PromQuery(ctx, req.(*PromQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_PromQueryRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromQueryRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PromQueryRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_PromQueryRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PromQueryRange(ctx, req.(*PromQueryRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_PromListAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromListAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PromListAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_PromListAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PromListAlerts(ctx, req.(*PromListAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_PromListTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromListTargetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PromListTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_PromListTargets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PromListTargets(ctx, req.(*PromListTargetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GrafanaListDashboards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrafanaListDashboardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GrafanaListDashboards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GrafanaListDashboards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GrafanaListDashboards(ctx, req.(*GrafanaListDashboardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GrafanaGetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrafanaGetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GrafanaGetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GrafanaGetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GrafanaGetDashboard(ctx, req.(*GrafanaGetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GrafanaListDataSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrafanaListDataSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GrafanaListDataSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GrafanaListDataSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GrafanaListDataSources(ctx, req.(*GrafanaListDataSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_LokiQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LokiQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).LokiQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_LokiQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).LokiQuery(ctx, req.(*LokiQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_LokiQueryRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LokiQueryRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).LokiQueryRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_LokiQueryRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).LokiQueryRange(ctx, req.(*LokiQueryRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ESListIndices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ESListIndicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ESListIndices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ESListIndices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ESListIndices(ctx, req.(*ESListIndicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ESSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ESSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ESSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ESSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ESSearch(ctx, req.(*ESSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ESHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ESHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ESHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ESHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ESHealth(ctx, req.(*ESHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_OSListIndices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ESListIndicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).OSListIndices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_OSListIndices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).OSListIndices(ctx, req.(*ESListIndicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_OSSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ESSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).OSSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_OSSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).OSSearch(ctx, req.(*ESSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_OSHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ESHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).OSHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_OSHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).OSHealth(ctx, req.(*ESHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_KibanaListSavedObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KibanaListSavedObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).KibanaListSavedObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_KibanaListSavedObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).KibanaListSavedObjects(ctx, req.(*KibanaListSavedObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_KibanaListDashboards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KibanaListDashboardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).KibanaListDashboards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_KibanaListDashboards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).KibanaListDashboards(ctx, req.(*KibanaListDashboardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_FluentdGetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FluentdMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).FluentdGetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_FluentdGetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).FluentdGetMetrics(ctx, req.(*FluentdMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_FluentdGetPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FluentdPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).FluentdGetPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_FluentdGetPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).FluentdGetPlugins(ctx, req.(*FluentdPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ReportAuditCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportAuditCountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ReportAuditCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ReportAuditCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ReportAuditCounts(ctx, req.(*ReportAuditCountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devops_portal.agent.v1.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AgentMetadata",
			Handler:    _Agent_AgentMetadata_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Agent_Heartbeat_Handler,
		},
		{
			MethodName: "RenewCert",
			Handler:    _Agent_RenewCert_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _Agent_ListNodes_Handler,
		},
		{
			MethodName: "ListNamespaces",
			Handler:    _Agent_ListNamespaces_Handler,
		},
		{
			MethodName: "ListPods",
			Handler:    _Agent_ListPods_Handler,
		},
		{
			MethodName: "GetPod",
			Handler:    _Agent_GetPod_Handler,
		},
		{
			MethodName: "ListWorkloads",
			Handler:    _Agent_ListWorkloads_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _Agent_ListServices_Handler,
		},
		{
			MethodName: "ListIngresses",
			Handler:    _Agent_ListIngresses_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _Agent_ListEvents_Handler,
		},
		{
			MethodName: "ListCRDs",
			Handler:    _Agent_ListCRDs_Handler,
		},
		{
			MethodName: "GetYaml",
			Handler:    _Agent_GetYaml_Handler,
		},
		{
			MethodName: "ArgoListApplications",
			Handler:    _Agent_ArgoListApplications_Handler,
		},
		{
			MethodName: "ArgoGetApplication",
			Handler:    _Agent_ArgoGetApplication_Handler,
		},
		{
			MethodName: "ArgoListAppProjects",
			Handler:    _Agent_ArgoListAppProjects_Handler,
		},
		{
			MethodName: "ArgoListApplicationSets",
			Handler:    _Agent_ArgoListApplicationSets_Handler,
		},
		{
			MethodName: "PromQuery",
			Handler:    _Agent_PromQuery_Handler,
		},
		{
			MethodName: "PromQueryRange",
			Handler:    _Agent_PromQueryRange_Handler,
		},
		{
			MethodName: "PromListAlerts",
			Handler:    _Agent_PromListAlerts_Handler,
		},
		{
			MethodName: "PromListTargets",
			Handler:    _Agent_PromListTargets_Handler,
		},
		{
			MethodName: "GrafanaListDashboards",
			Handler:    _Agent_GrafanaListDashboards_Handler,
		},
		{
			MethodName: "GrafanaGetDashboard",
			Handler:    _Agent_GrafanaGetDashboard_Handler,
		},
		{
			MethodName: "GrafanaListDataSources",
			Handler:    _Agent_GrafanaListDataSources_Handler,
		},
		{
			MethodName: "LokiQuery",
			Handler:    _Agent_LokiQuery_Handler,
		},
		{
			MethodName: "LokiQueryRange",
			Handler:    _Agent_LokiQueryRange_Handler,
		},
		{
			MethodName: "ESListIndices",
			Handler:    _Agent_ESListIndices_Handler,
		},
		{
			MethodName: "ESSearch",
			Handler:    _Agent_ESSearch_Handler,
		},
		{
			MethodName: "ESHealth",
			Handler:    _Agent_ESHealth_Handler,
		},
		{
			MethodName: "OSListIndices",
			Handler:    _Agent_OSListIndices_Handler,
		},
		{
			MethodName: "OSSearch",
			Handler:    _Agent_OSSearch_Handler,
		},
		{
			MethodName: "OSHealth",
			Handler:    _Agent_OSHealth_Handler,
		},
		{
			MethodName: "KibanaListSavedObjects",
			Handler:    _Agent_KibanaListSavedObjects_Handler,
		},
		{
			MethodName: "KibanaListDashboards",
			Handler:    _Agent_KibanaListDashboards_Handler,
		},
		{
			MethodName: "FluentdGetMetrics",
			Handler:    _Agent_FluentdGetMetrics_Handler,
		},
		{
			MethodName: "FluentdGetPlugins",
			Handler:    _Agent_FluentdGetPlugins_Handler,
		},
		{
			MethodName: "ReportAuditCounts",
			Handler:    _Agent_ReportAuditCounts_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPodLogs",
			Handler:       _Agent_StreamPodLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchEvents",
			Handler:       _Agent_WatchEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "devops_portal/agent/v1/agent.proto",
}
